import { createElement, useEffect, useState, type ReactNode } from 'react'
import { personal } from './data/personal'
import { projects } from './data/projects'
import { skills } from './data/skills'
import { certifications } from './data/certifications'
import { socialLinks } from './data/socialLinks'
import './App.css'

const navItems = ['about', 'skills', 'projects', 'hackathon', 'certifications', 'contact']
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7 } } }
const Icon = ({ children }: { children: string }) => <span aria-hidden="true" className="icon-fallback">{children}</span>
const ArrowUpRight = (_props?: Record<string, unknown>) => <Icon>↗</Icon>
const Check = (_props?: Record<string, unknown>) => <Icon>+</Icon>
const ChevronDown = (_props?: Record<string, unknown>) => <Icon>↓</Icon>
const ExternalLink = (_props?: Record<string, unknown>) => <Icon>↗</Icon>
const Github = (_props?: Record<string, unknown>) => <Icon>GH</Icon>
const Linkedin = (_props?: Record<string, unknown>) => <Icon>in</Icon>
const Mail = (_props?: Record<string, unknown>) => <Icon>@</Icon>
const Menu = (_props?: Record<string, unknown>) => <Icon>≡</Icon>
const Phone = (_props?: Record<string, unknown>) => <Icon>tel</Icon>
const X = (_props?: Record<string, unknown>) => <Icon>×</Icon>
const motion = new Proxy({}, {
  get: (_, tag: string) => (props: Record<string, any>) => {
    const { variants, initial, animate, whileInView, viewport, transition, ...htmlProps } = props
    void variants
    void initial
    void animate
    void whileInView
    void viewport
    void transition
    return createElement(tag, htmlProps, props.children as ReactNode)
  }
}) as Record<string, (props: Record<string, any>) => ReactNode>

function App() {
  const [scrolled, setScrolled] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [darkMode, setDarkMode] = useState(false)
  const [previewProject, setPreviewProject] = useState<typeof projects[number] | null>(null)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const goTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <div className={`site-shell ${darkMode ? 'theme-dark' : ''}`}>
    <header className={`navbar ${scrolled ? 'navbar-scrolled' : ''}`}><button className="wordmark" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>K NAVEEN NAYAK</button><nav className="desktop-nav" aria-label="Primary navigation">{navItems.map((item) => <button key={item} onClick={() => goTo(item)}>{item}</button>)}<button className="theme-toggle" onClick={() => setDarkMode(!darkMode)} aria-label={`Switch to ${darkMode ? 'light' : 'dark'} mode`}><span>{darkMode ? 'LIGHT' : 'DARK'}</span><i /></button></nav><button className="menu-toggle" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map((item) => <button key={item} onClick={() => goTo(item)}>{item}</button>)}<button className="theme-toggle" onClick={() => setDarkMode(!darkMode)}>{darkMode ? 'LIGHT MODE' : 'DARK MODE'}<i /></button></nav>}</header>
    <main>
      <section className="hero" aria-labelledby="hero-title"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-grid" /><div className="hero-content"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }}>01 / INTRODUCTION</motion.p><motion.h1 id="hero-title" initial={{ opacity: 0, y: 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>K NAVEEN<br /><span>NAYAK</span></motion.h1><motion.div className="hero-bottom" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}><p className="hero-role">AI &amp; Data Science Student.<br /><em>Building ideas into real-world solutions.</em></p><p className="hero-meta">{personal.degree}<br />{personal.university}</p><p className="hero-note">Future Software Engineer<br />focused on practical technology.</p></motion.div><div className="hero-actions"><button className="button button-dark" onClick={() => goTo('projects')}>VIEW MY WORK <ArrowUpRight size={16} /></button><button className="text-button" onClick={() => goTo('contact')}>LET'S CONNECT <ArrowUpRight size={16} /></button></div></div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><ChevronDown size={16} /></div></section>
      <section className="section" id="about"><SectionIntro index="02" title="About me" description="A curious builder at the intersection of software, data, and intelligent systems." /><div className="about-grid"><motion.h2 variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true }}>Learning.<br /><span>Building.</span><br />Improving.</motion.h2><motion.div className="about-copy" variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true }}><p>{personal.bio}</p><div className="info-grid">{[['Education', personal.degree], ['University', personal.university], ['Location', 'Bengaluru, India'], ['Goal', 'Software Engineer']].map(([label, value]) => <div className="info-item" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></motion.div></div></section>
      <section className="section" id="skills"><SectionIntro index="03" title="Skills" description="Technologies and tools I'm continuously learning and building with." /><div className="skills-list">{skills.map((group, index) => <motion.div className="skill-row" key={group.label} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true }} transition={{ delay: index * 0.06 }}><h3>{group.label}</h3><div className="skill-tags">{group.items.map((skill) => <span key={skill}>{skill}</span>)}</div></motion.div>)}</div></section>
      <section className="section" id="projects"><SectionIntro index="04" title="Selected projects" description="Real projects built while learning, experimenting, and solving practical problems." /><div className="project-list">{projects.map((project) => <ProjectCard key={project.title} project={project} onPreview={() => setPreviewProject(project)} />)}</div></section>
      <section className="hackathon-section" id="hackathon"><div className="waveform" aria-hidden="true">{Array.from({ length: 38 }, (_, i) => <i key={i} style={{ height: `${18 + ((i * 29) % 68)}%` }} />)}</div><div className="hackathon-inner"><p className="eyebrow light">05 / FEATURED CHALLENGE</p><p className="hackathon-code">SMART INDIA HACKATHON <span>PS 26104</span></p><h2>AI-powered real-time detection and prevention of <em>voice cloning impersonation attacks.</em></h2><p className="hackathon-description">Working on an AI and cybersecurity solution focused on detecting and preventing voice-cloning impersonation attacks.</p><div className="area-list">{['Artificial Intelligence', 'Machine Learning', 'Cybersecurity', 'Voice Cloning Detection', 'Risk Analysis'].map((area) => <span key={area}><Check size={15} />{area}</span>)}</div></div></section>
      <section className="section" id="certifications"><SectionIntro index="06" title="Certifications" description="Milestones that mark the way forward." /><div className="cert-grid">{certifications.map((cert, index) => <motion.article className="cert-card" key={cert.title} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true }} transition={{ delay: index * 0.05 }}><div className="cert-top"><span>CREDENTIAL / {String(index + 1).padStart(2, '0')}</span><span>{cert.date}</span></div><h3>{cert.title}</h3><p className="issuer">{cert.issuer}</p>{'description' in cert && cert.description && <p className="cert-description">{cert.description}</p>}{cert.skills.length > 0 && <div className="cert-skills">{cert.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>}{'url' in cert && cert.url && <a href={cert.url} target="_blank" rel="noreferrer" className="inline-link">VIEW CREDENTIAL <ExternalLink size={14} /></a>}</motion.article>)}</div></section>
      <section className="presence-section"><div className="presence-heading"><p className="eyebrow">07 / ONLINE PRESENCE</p><h2>Code. Build.<br /><em>Improve.</em></h2></div><div className="presence-grid"><SocialCard icon={<Github />} title="GitHub" description="My GitHub profile showcasing projects, coding practice, and continuous learning in Python, C++, DSA, AI/ML, and IoT." url={socialLinks.github} /><SocialCard icon={<Linkedin />} title="LinkedIn" description="My professional profile featuring my projects, certifications, learning journey, and technical interests." url={socialLinks.linkedin} />{socialLinks.hackerrank && <SocialCard icon={<ArrowUpRight />} title="HackerRank" description="My coding practice and problem-solving profile." url={socialLinks.hackerrank} />}</div></section>
      <section className="featured-section"><div><p className="eyebrow">08 / THE BIGGER PICTURE</p><h2>Explore my<br /><em>journey.</em></h2><p>Explore my projects, technical skills, certifications, and continuous learning journey.</p><a className="button button-light" href={socialLinks.portfolio} target="_blank" rel="noreferrer">VISIT PORTFOLIO <ArrowUpRight size={16} /></a></div><div className="featured-mark">KN<span>/</span>26</div></section>
      <section className="contact-section" id="contact"><p className="eyebrow">09 / GET IN TOUCH</p><h2>Let's build<br /><em>something.</em></h2><p className="contact-lede">Always open to learning, collaborating, and building meaningful projects.</p><div className="contact-actions"><a className="button button-dark" href={socialLinks.email}>EMAIL ME <ArrowUpRight size={16} /></a><a className="text-button" href={socialLinks.linkedin} target="_blank" rel="noreferrer">LINKEDIN <ArrowUpRight size={16} /></a><a className="text-button" href={socialLinks.github} target="_blank" rel="noreferrer">GITHUB <ArrowUpRight size={16} /></a></div><div className="contact-details"><a href={socialLinks.email}><Mail size={16} />naveennayak2817@gmail.com</a><a href={socialLinks.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16} />LinkedIn</a><a href={socialLinks.github} target="_blank" rel="noreferrer"><Github size={16} />GitHub</a><a className="phone-link" href={socialLinks.phone}><Phone size={15} />8073134667</a></div></section>
    </main>{previewProject && <div className="preview-backdrop" role="presentation" onClick={() => setPreviewProject(null)}><article className="preview-modal" role="dialog" aria-modal="true" aria-labelledby="preview-title" onClick={(event) => event.stopPropagation()}><button className="preview-close" aria-label="Close project preview" onClick={() => setPreviewProject(null)}><X /></button><p className="eyebrow">PROJECT PREVIEW / {previewProject.number}</p><h2 id="preview-title">{previewProject.title}</h2><p className="preview-category">{previewProject.category}</p><p className="preview-description">{previewProject.description}</p><div className="preview-tech">{previewProject.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div><div className={`preview-art preview-art-${previewProject.kind}`}><span>{previewProject.kind === 'parking' ? 'LIVE SLOT MONITOR' : previewProject.kind === 'health' ? 'CARE / ON TIME' : 'CREATE / SHAPE / EDIT'}</span></div></article></div>}<footer><span>K NAVEEN NAYAK</span><span>B.Tech AI &amp; Data Science · REVA University</span><span>Building. Learning. Growing. · © 2026</span></footer>
  </div>
}

function SectionIntro({ index, title, description }: { index: string; title: string; description: string }) { return <div className="section-intro"><p className="eyebrow">{index} / {title.toUpperCase()}</p><h2>{title}</h2><p>{description}</p></div> }
function ProjectCard({ project, onPreview }: { project: typeof projects[number]; onPreview: () => void }) { return <motion.article className={`project-card project-${project.kind}`} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true }}><div className="project-copy"><div className="project-number">{project.number} / 03</div><p className="project-category">{project.category}</p><h3>{project.title}</h3><p>{project.description}</p><div className="project-tech">{project.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div><button className="preview-trigger" onClick={onPreview}>PREVIEW PROJECT <ArrowUpRight size={14} /></button>{project.url && <a className="inline-link" href={project.url} target="_blank" rel="noreferrer">VIEW PROJECT <ArrowUpRight size={14} /></a>}</div><div className="project-visual" aria-label={`${project.title} visualization`}>{project.kind === 'parking' && <div className="parking-visual">{[1, 2, 3, 4].map((slot) => <div className={`parking-slot ${slot === 2 ? 'occupied' : ''}`} key={slot}><span>{slot === 2 ? 'OCCUPIED' : 'AVAILABLE'}</span></div>)}</div>}{project.kind === 'health' && <div className="health-visual"><div className="health-pulse" /><strong>Home<span>Cure</span></strong><small>Care, on time.</small><div className="health-lines"><i /><i /><i /></div></div>}{project.kind === 'graphics' && <div className="graphics-visual"><div className="shape shape-circle" /><div className="shape shape-square" /><div className="shape shape-line" /><span>2D / EDITOR</span></div>}</div></motion.article> }
function SocialCard({ icon, title, description, url }: { icon: ReactNode; title: string; description: string; url: string }) { return <a className="social-card" href={url} target="_blank" rel="noreferrer"><div className="social-icon">{icon}</div><h3>{title}<ArrowUpRight size={18} /></h3><p>{description}</p><span>VIEW {title.toUpperCase()} <ArrowUpRight size={14} /></span></a> }
export default App
